### ISSUE TITLE
isKeyframe is returning undefined

### ISSUE THREAD

**Issue by Tenpi** [jscodec/jswebm#33]
Hi, I've found that the `isKeyframe` property is returning undefined for most of the webm videos I've tried, this causes an error with the VideoDecoder because it needs to start decoding on a keyframe. Can you look into it?
<img width="336" alt="Screen Shot 2022-04-12 at 8 28 25 PM" src="https://user-images.githubusercontent.com/37512637/163076029-06d8b054-7f97-4f65-b4af-a9f7ca6a62f8.png">

Here's a example video if you need one. 
https://drive.google.com/file/d/1d3P2nzexyQA8yKTgticgLddqbPn_zIKP/view?usp=sharing

**Comment by animeshk874** [comment]
Hi @Tenpi, this issue was fixed in this PR -> https://github.com/jscodec/jswebm/pull/25
However, you are still getting this issue because the **npm package is not updated.** So you are still using an older version of jswebm, where the `undefined` issue isn't solved. I think @brianxautumn owns this repo and he has the access to publish it to npm. In the meanwhile, if you want to use this repo, you can fork it, and use the github url in the package.json to install this package.

**Comment by Tenpi** [comment]
Ok, I apologize for missing that this was already fixed. I can see that the npm package hasn't been updated in 2 years. 

@brianxautumn, if you are no longer interested in maintaining this project, you should add someone else with write access to the npm package. Thanks.

For now I am going to use my fork of this project.

**Comment by brianxautumn** [comment]
HI, I'll try to get a new revision published soon! and yes need help maintaining

**Comment by Achuttarsing** [comment]
> Ok, I apologize for missing that this was already fixed. I can see that the npm package hasn't been updated in 2 years.
> 
> @brianxautumn, if you are no longer interested in maintaining this project, you should add someone else with write access to the npm package. Thanks.
> 
> For now I am going to use my fork of this project.

Your fork makes the lib being able to work with Nuxt, thanks! Nice fix
